export interface MedicalTerm {
  conceptId: string
  category: 'drug' | 'symptom' | 'condition' | 'procedure'
  terms: Record<string, {
    formal: string
    common: string[]
    brandNames?: string[]
  }>
}

export const MEDICAL_TERMS: MedicalTerm[] = [
  /* ──────────────────────────────────────────────────────────
     DRUGS (15)
     ────────────────────────────────────────────────────────── */
  {
    conceptId: 'DRUG-001',
    category: 'drug',
    terms: {
      en: { formal: 'Ibuprofen', common: ['pain reliever', 'anti-inflammatory'], brandNames: ['Advil', 'Motrin'] },
      es: { formal: 'Ibuprofeno', common: ['antiinflamatorio', 'pastilla para el dolor'], brandNames: ['Advil', 'Motrin', 'Actron'] },
      fr: { formal: 'Ibuprofène', common: ['anti-douleur', 'anti-inflammatoire'], brandNames: ['Nurofen', 'Advil'] },
      ar: { formal: 'إيبوبروفين', common: ['مسكّن ألم', 'مضاد التهاب'], brandNames: ['بروفين', 'بروفينال'] },
      zh: { formal: '布洛芬', common: ['止痛药', '消炎药'], brandNames: ['芬必得', '美林'] },
      hi: { formal: 'इबुप्रोफ़ेन', common: ['दर्द की गोली', 'सूजन की दवा'], brandNames: ['ब्रूफ़ेन', 'इबुजेसिक'] },
      tl: { formal: 'Ibuprofen', common: ['pampawala ng sakit', 'pang-inflammasyon'], brandNames: ['Advil', 'Medicol'] },
      pt: { formal: 'Ibuprofeno', common: ['anti-inflamatório', 'analgésico'], brandNames: ['Advil', 'Alivium', 'Ibupril'] },
    },
  },
  {
    conceptId: 'DRUG-002',
    category: 'drug',
    terms: {
      en: { formal: 'Acetaminophen', common: ['pain reliever', 'fever reducer'], brandNames: ['Tylenol'] },
      es: { formal: 'Paracetamol', common: ['pastilla para la fiebre', 'analgésico'], brandNames: ['Tylenol', 'Tempra'] },
      fr: { formal: 'Paracétamol', common: ['antidouleur', 'antipyrétique'], brandNames: ['Doliprane', 'Efferalgan', 'Dafalgan'] },
      ar: { formal: 'باراسيتامول', common: ['مسكّن', 'خافض حرارة'], brandNames: ['بانادول', 'أدول', 'سيتامول'] },
      zh: { formal: '对乙酰氨基酚', common: ['退烧药', '止痛片'], brandNames: ['泰诺', '必理痛'] },
      hi: { formal: 'पैरासिटामोल', common: ['बुखार की गोली', 'दर्द की दवा'], brandNames: ['क्रोसिन', 'डोलो', 'कैलपोल'] },
      tl: { formal: 'Paracetamol', common: ['gamot sa lagnat', 'pampaalis ng sakit'], brandNames: ['Biogesic', 'Tempra', 'Tylenol'] },
      pt: { formal: 'Paracetamol', common: ['analgésico', 'remédio para febre'], brandNames: ['Tylenol', 'Dorflex'] },
    },
  },
  {
    conceptId: 'DRUG-003',
    category: 'drug',
    terms: {
      en: { formal: 'Amoxicillin', common: ['antibiotic', 'penicillin-type antibiotic'], brandNames: ['Amoxil', 'Trimox'] },
      es: { formal: 'Amoxicilina', common: ['antibiótico', 'penicilina'], brandNames: ['Amoxil', 'Clamoxyl'] },
      fr: { formal: 'Amoxicilline', common: ['antibiotique', 'pénicilline'], brandNames: ['Clamoxyl', 'Amoxil'] },
      ar: { formal: 'أموكسيسيلين', common: ['مضاد حيوي', 'بنسلين'], brandNames: ['أموكسيل', 'أوغمنتين'] },
      zh: { formal: '阿莫西林', common: ['抗生素', '消炎药'], brandNames: ['阿莫仙', '再林'] },
      hi: { formal: 'एमोक्सिसिलिन', common: ['एंटीबायोटिक', 'संक्रमण की दवा'], brandNames: ['मोक्स', 'नोवामॉक्स'] },
      tl: { formal: 'Amoxicillin', common: ['antibiyotiko', 'gamot sa impeksyon'], brandNames: ['Amoxil'] },
      pt: { formal: 'Amoxicilina', common: ['antibiótico', 'penicilina'], brandNames: ['Amoxil', 'Novocilin'] },
    },
  },
  {
    conceptId: 'DRUG-004',
    category: 'drug',
    terms: {
      en: { formal: 'Omeprazole', common: ['acid reducer', 'stomach pill', 'proton pump inhibitor'], brandNames: ['Prilosec', 'Losec'] },
      es: { formal: 'Omeprazol', common: ['pastilla para el estómago', 'protector gástrico', 'antiácido'], brandNames: ['Prilosec', 'Losec', 'Inhibitol'] },
      fr: { formal: 'Oméprazole', common: ['anti-acide', 'protecteur gastrique'], brandNames: ['Mopral', 'Losec'] },
      ar: { formal: 'أوميبرازول', common: ['دواء المعدة', 'مضاد الحموضة'], brandNames: ['لوسك', 'أوميز'] },
      zh: { formal: '奥美拉唑', common: ['胃药', '抑酸药'], brandNames: ['洛赛克', '奥克'] },
      hi: { formal: 'ओमेप्राज़ोल', common: ['पेट की दवा', 'एसिडिटी की गोली'], brandNames: ['ओमेज़', 'ओसिड'] },
      tl: { formal: 'Omeprazole', common: ['gamot sa asido ng tiyan', 'gamot sa sikmura'], brandNames: ['Prilosec', 'Losec'] },
      pt: { formal: 'Omeprazol', common: ['remédio para o estômago', 'protetor gástrico'], brandNames: ['Losec', 'Peprazol'] },
    },
  },
  {
    conceptId: 'DRUG-005',
    category: 'drug',
    terms: {
      en: { formal: 'Metformin', common: ['diabetes medicine', 'blood sugar pill'], brandNames: ['Glucophage', 'Fortamet'] },
      es: { formal: 'Metformina', common: ['pastilla para la diabetes', 'medicina para el azúcar'], brandNames: ['Glucophage', 'Dabex'] },
      fr: { formal: 'Metformine', common: ['médicament pour le diabète', 'antidiabétique'], brandNames: ['Glucophage', 'Stagid'] },
      ar: { formal: 'ميتفورمين', common: ['دواء السكري', 'حبة السكر'], brandNames: ['غلوكوفاج', 'سيدوفاج'] },
      zh: { formal: '二甲双胍', common: ['降糖药', '糖尿病药'], brandNames: ['格华止', '美迪康'] },
      hi: { formal: 'मेटफ़ॉर्मिन', common: ['शुगर की गोली', 'डायबिटीज़ की दवा'], brandNames: ['ग्लूकोफ़ेज', 'ग्लाइसीफ़ेज'] },
      tl: { formal: 'Metformin', common: ['gamot sa diyabetis', 'gamot sa asukal sa dugo'], brandNames: ['Glucophage'] },
      pt: { formal: 'Metformina', common: ['remédio para diabetes', 'remédio para açúcar no sangue'], brandNames: ['Glucoformin', 'Glifage'] },
    },
  },
  {
    conceptId: 'DRUG-006',
    category: 'drug',
    terms: {
      en: { formal: 'Lisinopril', common: ['blood pressure medicine', 'ACE inhibitor'], brandNames: ['Zestril', 'Prinivil'] },
      es: { formal: 'Lisinopril', common: ['pastilla para la presión', 'medicamento para la presión arterial'], brandNames: ['Zestril', 'Prinivil'] },
      fr: { formal: 'Lisinopril', common: ['médicament pour la tension', 'antihypertenseur'], brandNames: ['Zestril', 'Prinivil'] },
      ar: { formal: 'ليسينوبريل', common: ['دواء الضغط', 'حبة الضغط'], brandNames: ['زيستريل'] },
      zh: { formal: '赖诺普利', common: ['降压药', '血压药'], brandNames: ['捷赐瑞'] },
      hi: { formal: 'लिसिनोप्रिल', common: ['बीपी की दवा', 'ब्लड प्रेशर की गोली'], brandNames: ['ज़ेस्ट्रिल'] },
      tl: { formal: 'Lisinopril', common: ['gamot sa alta presyon', 'gamot sa dugo'], brandNames: ['Zestril'] },
      pt: { formal: 'Lisinopril', common: ['remédio para pressão', 'anti-hipertensivo'], brandNames: ['Zestril', 'Prinivil'] },
    },
  },
  {
    conceptId: 'DRUG-007',
    category: 'drug',
    terms: {
      en: { formal: 'Loratadine', common: ['allergy medicine', 'antihistamine'], brandNames: ['Claritin', 'Alavert'] },
      es: { formal: 'Loratadina', common: ['pastilla para la alergia', 'antialérgico'], brandNames: ['Clarityne', 'Sensibit'] },
      fr: { formal: 'Loratadine', common: ['antihistaminique', 'anti-allergique'], brandNames: ['Clarityne'] },
      ar: { formal: 'لوراتادين', common: ['دواء الحساسية', 'مضاد هيستامين'], brandNames: ['كلاريتين'] },
      zh: { formal: '氯雷他定', common: ['过敏药', '抗过敏药'], brandNames: ['开瑞坦'] },
      hi: { formal: 'लोराटैडीन', common: ['एलर्जी की दवा', 'खुजली की गोली'], brandNames: ['एलेरिड', 'लोरफ़ास्ट'] },
      tl: { formal: 'Loratadine', common: ['gamot sa allergy', 'antihistamine'], brandNames: ['Claritin', 'Allerta'] },
      pt: { formal: 'Loratadina', common: ['antialérgico', 'remédio para alergia'], brandNames: ['Claritin', 'Loralerg'] },
    },
  },
  {
    conceptId: 'DRUG-008',
    category: 'drug',
    terms: {
      en: { formal: 'Ciprofloxacin', common: ['antibiotic', 'fluoroquinolone'], brandNames: ['Cipro'] },
      es: { formal: 'Ciprofloxacino', common: ['antibiótico', 'quinolona'], brandNames: ['Cipro', 'Ciproxina'] },
      fr: { formal: 'Ciprofloxacine', common: ['antibiotique', 'fluoroquinolone'], brandNames: ['Ciflox'] },
      ar: { formal: 'سيبروفلوكساسين', common: ['مضاد حيوي', 'مضاد للجراثيم'], brandNames: ['سيبرو', 'سيبروسين'] },
      zh: { formal: '环丙沙星', common: ['消炎药', '抗菌药'], brandNames: ['环丙沙星片'] },
      hi: { formal: 'सिप्रोफ़्लॉक्सासिन', common: ['एंटीबायोटिक', 'इन्फ़ेक्शन की दवा'], brandNames: ['सिप्लॉक्स', 'ज़ॉक्स'] },
      tl: { formal: 'Ciprofloxacin', common: ['antibiyotiko', 'gamot sa impeksyon'], brandNames: ['Cipro', 'Ciprobay'] },
      pt: { formal: 'Ciprofloxacino', common: ['antibiótico', 'fluoroquinolona'], brandNames: ['Cipro', 'Cipronil'] },
    },
  },
  {
    conceptId: 'DRUG-009',
    category: 'drug',
    terms: {
      en: { formal: 'Prednisone', common: ['steroid', 'corticosteroid', 'anti-inflammatory steroid'], brandNames: ['Deltasone', 'Rayos'] },
      es: { formal: 'Prednisona', common: ['esteroide', 'corticoide', 'cortisona'], brandNames: ['Meticorten'] },
      fr: { formal: 'Prednisone', common: ['corticoïde', 'cortisone'], brandNames: ['Cortancyl'] },
      ar: { formal: 'بريدنيزون', common: ['كورتيزون', 'ستيرويد'], brandNames: ['هوستاكورتين'] },
      zh: { formal: '泼尼松', common: ['激素', '类固醇', '强的松'], brandNames: ['强的松片'] },
      hi: { formal: 'प्रेडनिसोन', common: ['स्टेरॉयड', 'कॉर्टिसोन'], brandNames: ['ओमनाकोर्टिल'] },
      tl: { formal: 'Prednisone', common: ['steroid', 'gamot sa pamamaga'], brandNames: ['Deltasone'] },
      pt: { formal: 'Prednisona', common: ['corticoide', 'esteroide'], brandNames: ['Meticorten', 'Predsim'] },
    },
  },
  {
    conceptId: 'DRUG-010',
    category: 'drug',
    terms: {
      en: { formal: 'Albuterol', common: ['inhaler', 'rescue inhaler', 'breathing medicine'], brandNames: ['Ventolin', 'ProAir', 'Proventil'] },
      es: { formal: 'Salbutamol', common: ['inhalador', 'aerosol para el asma', 'bomba'], brandNames: ['Ventolin', 'Salbutamol'] },
      fr: { formal: 'Salbutamol', common: ['inhalateur', 'pompe', 'bronchodilatateur'], brandNames: ['Ventoline'] },
      ar: { formal: 'سالبوتامول', common: ['بخاخ الربو', 'موسع شعب هوائية'], brandNames: ['فنتولين'] },
      zh: { formal: '沙丁胺醇', common: ['哮喘喷雾', '气管扩张剂', '喷雾器'], brandNames: ['万托林'] },
      hi: { formal: 'सैल्ब्युटामोल', common: ['इनहेलर', 'दमे की दवा', 'पंप'], brandNames: ['एस्थालिन', 'वेंटोलिन'] },
      tl: { formal: 'Salbutamol', common: ['inhaler', 'gamot sa hika', 'nebulizer'], brandNames: ['Ventolin'] },
      pt: { formal: 'Salbutamol', common: ['bombinha', 'inalador', 'broncodilatador'], brandNames: ['Aerolin'] },
    },
  },
  {
    conceptId: 'DRUG-011',
    category: 'drug',
    terms: {
      en: { formal: 'Insulin', common: ['diabetes injection', 'blood sugar shot'], brandNames: ['Humalog', 'Lantus', 'NovoLog', 'Humulin'] },
      es: { formal: 'Insulina', common: ['inyección para la diabetes', 'la insulina'], brandNames: ['Humalog', 'Lantus', 'Humulin'] },
      fr: { formal: 'Insuline', common: ['injection pour le diabète', 'piqûre'], brandNames: ['Humalog', 'Lantus', 'NovoRapid'] },
      ar: { formal: 'إنسولين', common: ['إبرة السكر', 'حقنة السكري'], brandNames: ['لانتوس', 'هيومالوغ', 'نوفورابيد'] },
      zh: { formal: '胰岛素', common: ['糖尿病针', '打胰岛素'], brandNames: ['优泌林', '来得时', '诺和锐'] },
      hi: { formal: 'इंसुलिन', common: ['शुगर का इंजेक्शन', 'डायबिटीज़ का सुई'], brandNames: ['ह्यूमालॉग', 'लैंटस', 'ह्यूमुलिन'] },
      tl: { formal: 'Insulin', common: ['iniksyon sa diyabetis', 'turok sa asukal'], brandNames: ['Humalog', 'Lantus'] },
      pt: { formal: 'Insulina', common: ['injeção para diabetes', 'aplicação de insulina'], brandNames: ['Humalog', 'Lantus', 'Novorapid'] },
    },
  },
  {
    conceptId: 'DRUG-012',
    category: 'drug',
    terms: {
      en: { formal: 'Aspirin', common: ['blood thinner', 'pain reliever'], brandNames: ['Bayer', 'Ecotrin'] },
      es: { formal: 'Aspirina', common: ['pastilla para el dolor', 'adelgazante de sangre'], brandNames: ['Aspirina', 'Bayer', 'Cafiaspirina'] },
      fr: { formal: 'Aspirine', common: ['antidouleur', 'fluidifiant sanguin'], brandNames: ['Aspégic', 'Kardégic'] },
      ar: { formal: 'أسبرين', common: ['مسكّن', 'مميّع الدم'], brandNames: ['أسبرين', 'جوسبرين'] },
      zh: { formal: '阿司匹林', common: ['退烧药', '止痛药', '血液稀释剂'], brandNames: ['拜阿司匹灵', '巴米尔'] },
      hi: { formal: 'एस्पिरिन', common: ['दर्द की गोली', 'खून पतला करने वाली दवा'], brandNames: ['डिस्प्रिन', 'एस्प्रो'] },
      tl: { formal: 'Aspirin', common: ['pampaalis ng sakit', 'pampalabnaw ng dugo'], brandNames: ['Bayer Aspirin'] },
      pt: { formal: 'Aspirina', common: ['analgésico', 'afinador do sangue'], brandNames: ['Aspirina', 'AAS', 'Bufferin'] },
    },
  },
  {
    conceptId: 'DRUG-013',
    category: 'drug',
    terms: {
      en: { formal: 'Naproxen', common: ['pain reliever', 'anti-inflammatory'], brandNames: ['Aleve', 'Naprosyn'] },
      es: { formal: 'Naproxeno', common: ['antiinflamatorio', 'pastilla para el dolor'], brandNames: ['Flanax', 'Naxen'] },
      fr: { formal: 'Naproxène', common: ['anti-inflammatoire', 'antidouleur'], brandNames: ['Apranax', 'Naprosyne'] },
      ar: { formal: 'نابروكسين', common: ['مسكّن ألم', 'مضاد التهاب'], brandNames: ['نابروسين'] },
      zh: { formal: '萘普生', common: ['止痛药', '消炎止痛'], brandNames: ['萘普生片'] },
      hi: { formal: 'नेप्रोक्सन', common: ['दर्द की दवा', 'सूजन की गोली'], brandNames: ['नेप्रोसिन', 'नैप्रा'] },
      tl: { formal: 'Naproxen', common: ['pampawala ng sakit', 'anti-inflammatoire'], brandNames: ['Aleve', 'Flanax'] },
      pt: { formal: 'Naproxeno', common: ['anti-inflamatório', 'analgésico'], brandNames: ['Flanax', 'Naprosyn'] },
    },
  },
  {
    conceptId: 'DRUG-014',
    category: 'drug',
    terms: {
      en: { formal: 'Ranitidine', common: ['heartburn medicine', 'acid blocker'], brandNames: ['Zantac'] },
      es: { formal: 'Ranitidina', common: ['pastilla para la acidez', 'antiácido'], brandNames: ['Zantac', 'Ranisen'] },
      fr: { formal: 'Ranitidine', common: ['anti-acide', 'médicament pour les brûlures d\'estomac'], brandNames: ['Azantac'] },
      ar: { formal: 'رانيتيدين', common: ['دواء الحموضة', 'حبة المعدة'], brandNames: ['زانتاك'] },
      zh: { formal: '雷尼替丁', common: ['胃药', '抗酸药'], brandNames: ['善胃得'] },
      hi: { formal: 'रैनिटिडीन', common: ['एसिडिटी की दवा', 'पेट की गोली'], brandNames: ['ज़ैन्टैक', 'अल्सेरैन'] },
      tl: { formal: 'Ranitidine', common: ['gamot sa asidong tiyan', 'gamot sa heartburn'], brandNames: ['Zantac'] },
      pt: { formal: 'Ranitidina', common: ['remédio para azia', 'antiácido'], brandNames: ['Antak', 'Label'] },
    },
  },
  {
    conceptId: 'DRUG-015',
    category: 'drug',
    terms: {
      en: { formal: 'Azithromycin', common: ['antibiotic', 'Z-pack'], brandNames: ['Zithromax', 'Z-Pack'] },
      es: { formal: 'Azitromicina', common: ['antibiótico', 'pastilla de 3 días'], brandNames: ['Zithromax', 'Azitrocin'] },
      fr: { formal: 'Azithromycine', common: ['antibiotique', 'macrolide'], brandNames: ['Zithromax', 'Ordipha'] },
      ar: { formal: 'أزيثروميسين', common: ['مضاد حيوي', 'زيثروماكس'], brandNames: ['زيثروماكس', 'أزروليد'] },
      zh: { formal: '阿奇霉素', common: ['抗生素', '消炎药'], brandNames: ['希舒美'] },
      hi: { formal: 'एज़िथ्रोमाइसिन', common: ['एंटीबायोटिक', 'तीन दिन की दवा'], brandNames: ['ज़िथ्रोमैक्स', 'एज़ी'] },
      tl: { formal: 'Azithromycin', common: ['antibiyotiko', 'tatlong-araw na gamot'], brandNames: ['Zithromax'] },
      pt: { formal: 'Azitromicina', common: ['antibiótico', 'azitro'], brandNames: ['Zitromax', 'Azi'] },
    },
  },

  /* ──────────────────────────────────────────────────────────
     SYMPTOMS (20)
     ────────────────────────────────────────────────────────── */
  {
    conceptId: 'SYMP-001',
    category: 'symptom',
    terms: {
      en: { formal: 'Headache', common: ['head pain', 'my head hurts', 'head is pounding'] },
      es: { formal: 'Cefalea', common: ['dolor de cabeza', 'me duele la cabeza', 'jaqueca'] },
      fr: { formal: 'Céphalée', common: ['mal de tête', 'j\'ai mal à la tête'] },
      ar: { formal: 'صداع', common: ['وجع رأس', 'رأسي يؤلمني'] },
      zh: { formal: '头痛', common: ['头疼', '脑袋疼'] },
      hi: { formal: 'सिरदर्द', common: ['सिर में दर्द', 'सिर भारी लगना'] },
      tl: { formal: 'Sakit ng ulo', common: ['masakit ang ulo', 'sumasakit ang ulo ko'] },
      pt: { formal: 'Cefaleia', common: ['dor de cabeça', 'enxaqueca'] },
    },
  },
  {
    conceptId: 'SYMP-002',
    category: 'symptom',
    terms: {
      en: { formal: 'Fever', common: ['temperature', 'feeling hot', 'burning up'] },
      es: { formal: 'Fiebre', common: ['calentura', 'temperatura', 'estoy ardiendo'] },
      fr: { formal: 'Fièvre', common: ['température', 'j\'ai chaud', 'j\'ai de la fièvre'] },
      ar: { formal: 'حمّى', common: ['سخونة', 'حرارة', 'جسمي حار'] },
      zh: { formal: '发热', common: ['发烧', '体温高', '烧起来了'] },
      hi: { formal: 'बुखार', common: ['ज्वर', 'तपना', 'गरम लगना', 'ताप'] },
      tl: { formal: 'Lagnat', common: ['nilalagnat', 'mainit ang katawan'] },
      pt: { formal: 'Febre', common: ['temperatura', 'estou com febre', 'corpo quente'] },
    },
  },
  {
    conceptId: 'SYMP-003',
    category: 'symptom',
    terms: {
      en: { formal: 'Cough', common: ['coughing', 'hacking', 'dry cough', 'wet cough'] },
      es: { formal: 'Tos', common: ['tosiendo', 'tos seca', 'tos con flema', 'no paro de toser'] },
      fr: { formal: 'Toux', common: ['je tousse', 'toux sèche', 'toux grasse'] },
      ar: { formal: 'سعال', common: ['كحّة', 'كحّة ناشفة', 'كحّة مع بلغم'] },
      zh: { formal: '咳嗽', common: ['干咳', '咳痰', '咳得厉害'] },
      hi: { formal: 'खांसी', common: ['सूखी खांसी', 'बलगम वाली खांसी', 'खांस रहा हूँ'] },
      tl: { formal: 'Ubo', common: ['inuubo', 'tuyong ubo', 'may plema'] },
      pt: { formal: 'Tosse', common: ['tossindo', 'tosse seca', 'tosse com catarro'] },
    },
  },
  {
    conceptId: 'SYMP-004',
    category: 'symptom',
    terms: {
      en: { formal: 'Chest pain', common: ['chest hurts', 'tightness in chest', 'pressure in chest'] },
      es: { formal: 'Dolor de pecho', common: ['me duele el pecho', 'opresión en el pecho', 'dolor en el corazón'] },
      fr: { formal: 'Douleur thoracique', common: ['mal à la poitrine', 'douleur dans la poitrine', 'oppression'] },
      ar: { formal: 'ألم في الصدر', common: ['وجع صدر', 'ضيقة صدر', 'ألم في القلب'] },
      zh: { formal: '胸痛', common: ['胸口疼', '胸闷', '心口痛'] },
      hi: { formal: 'छाती में दर्द', common: ['सीने में दर्द', 'छाती में जकड़न', 'दिल में दर्द'] },
      tl: { formal: 'Sakit ng dibdib', common: ['masakit ang dibdib', 'masikip ang dibdib'] },
      pt: { formal: 'Dor no peito', common: ['dor torácica', 'aperto no peito', 'pontada no peito'] },
    },
  },
  {
    conceptId: 'SYMP-005',
    category: 'symptom',
    terms: {
      en: { formal: 'Nausea', common: ['feeling sick', 'queasy', 'feel like throwing up', 'upset stomach'] },
      es: { formal: 'Náusea', common: ['asco', 'ganas de vomitar', 'me siento mal del estómago', 'basca'] },
      fr: { formal: 'Nausée', common: ['envie de vomir', 'mal au cœur', 'haut-le-cœur'] },
      ar: { formal: 'غثيان', common: ['دوخة معدة', 'حاسس إني بستفرغ', 'معدتي مقلوبة'] },
      zh: { formal: '恶心', common: ['想吐', '反胃', '犯恶心'] },
      hi: { formal: 'मतली', common: ['जी मिचलाना', 'उल्टी जैसा लगना', 'मन घबराना'] },
      tl: { formal: 'Pagkasuka', common: ['nasusuka', 'gusto kong magsuka', 'nahihilo ang tiyan'] },
      pt: { formal: 'Náusea', common: ['enjoo', 'vontade de vomitar', 'estômago embrulhado'] },
    },
  },
  {
    conceptId: 'SYMP-006',
    category: 'symptom',
    terms: {
      en: { formal: 'Dizziness', common: ['dizzy', 'lightheaded', 'room is spinning', 'vertigo'] },
      es: { formal: 'Mareo', common: ['estoy mareado', 'se me va la cabeza', 'vértigo', 'me siento inestable'] },
      fr: { formal: 'Vertige', common: ['j\'ai la tête qui tourne', 'étourdi', 'vertiges'] },
      ar: { formal: 'دوخة', common: ['دوار', 'رأسي يدور', 'أحس بدوخة'] },
      zh: { formal: '头晕', common: ['眩晕', '天旋地转', '晕乎乎'] },
      hi: { formal: 'चक्कर', common: ['सिर घूमना', 'चक्कर आना', 'आँखों में अंधेरा'] },
      tl: { formal: 'Pagkahilo', common: ['nahihilo', 'umiikot ang paligid'] },
      pt: { formal: 'Tontura', common: ['tonto', 'cabeça girando', 'vertigem', 'zonzo'] },
    },
  },
  {
    conceptId: 'SYMP-007',
    category: 'symptom',
    terms: {
      en: { formal: 'Fatigue', common: ['tired', 'exhausted', 'no energy', 'worn out'] },
      es: { formal: 'Fatiga', common: ['cansancio', 'agotamiento', 'estoy agotado', 'no tengo energía'] },
      fr: { formal: 'Fatigue', common: ['épuisé', 'crevé', 'je n\'ai plus d\'énergie'] },
      ar: { formal: 'إرهاق', common: ['تعب', 'إنهاك', 'ما عندي طاقة'] },
      zh: { formal: '疲劳', common: ['累', '没力气', '浑身没劲', '疲惫'] },
      hi: { formal: 'थकान', common: ['थकावट', 'कमज़ोरी', 'ताक़त नहीं है', 'शरीर टूट रहा है'] },
      tl: { formal: 'Pagkapagod', common: ['pagod na pagod', 'walang lakas', 'nanghihina'] },
      pt: { formal: 'Fadiga', common: ['cansaço', 'exausto', 'sem energia', 'esgotado'] },
    },
  },
  {
    conceptId: 'SYMP-008',
    category: 'symptom',
    terms: {
      en: { formal: 'Dyspnea', common: ['shortness of breath', 'can\'t breathe', 'hard to breathe', 'winded'] },
      es: { formal: 'Disnea', common: ['falta de aire', 'me cuesta respirar', 'me ahogo', 'no puedo respirar'] },
      fr: { formal: 'Dyspnée', common: ['essoufflement', 'j\'ai du mal à respirer', 'je manque d\'air'] },
      ar: { formal: 'ضيق تنفّس', common: ['ما أقدر أتنفّس', 'نَفَسي ضيّق', 'كتمة'] },
      zh: { formal: '呼吸困难', common: ['喘不上气', '呼吸急促', '透不过气'] },
      hi: { formal: 'श्वास कष्ट', common: ['सांस फूलना', 'सांस नहीं आ रही', 'दम घुटना'] },
      tl: { formal: 'Hirap sa paghinga', common: ['hindi makahinga', 'nauubusan ng hininga', 'hingal'] },
      pt: { formal: 'Dispneia', common: ['falta de ar', 'dificuldade para respirar', 'não consigo respirar'] },
    },
  },
  {
    conceptId: 'SYMP-009',
    category: 'symptom',
    terms: {
      en: { formal: 'Back pain', common: ['my back hurts', 'backache', 'lower back pain'] },
      es: { formal: 'Dolor de espalda', common: ['me duele la espalda', 'dolor lumbar', 'dolor de cintura'] },
      fr: { formal: 'Lombalgie', common: ['mal de dos', 'j\'ai mal au dos', 'douleur lombaire'] },
      ar: { formal: 'ألم الظهر', common: ['وجع ظهر', 'ظهري يوجعني', 'ألم أسفل الظهر'] },
      zh: { formal: '背痛', common: ['腰疼', '后背疼', '腰酸背痛'] },
      hi: { formal: 'कमर दर्द', common: ['पीठ में दर्द', 'कमर में दर्द', 'पीठ दुख रही है'] },
      tl: { formal: 'Sakit ng likod', common: ['masakit ang likod', 'masakit ang baywang'] },
      pt: { formal: 'Lombalgia', common: ['dor nas costas', 'dor lombar', 'dor na coluna'] },
    },
  },
  {
    conceptId: 'SYMP-010',
    category: 'symptom',
    terms: {
      en: { formal: 'Pharyngitis', common: ['sore throat', 'throat hurts', 'scratchy throat'] },
      es: { formal: 'Faringitis', common: ['dolor de garganta', 'me duele la garganta', 'garganta irritada'] },
      fr: { formal: 'Pharyngite', common: ['mal de gorge', 'j\'ai mal à la gorge', 'gorge irritée'] },
      ar: { formal: 'التهاب البلعوم', common: ['وجع حلق', 'حلقي يؤلمني', 'التهاب حلق'] },
      zh: { formal: '咽炎', common: ['嗓子疼', '喉咙痛', '嗓子发炎'] },
      hi: { formal: 'गले में दर्द', common: ['गला दुख रहा है', 'गले में ख़राश', 'गला पक गया'] },
      tl: { formal: 'Pananakit ng lalamunan', common: ['masakit ang lalamunan', 'namamaga ang lalamunan'] },
      pt: { formal: 'Faringite', common: ['dor de garganta', 'garganta inflamada', 'garganta arranhando'] },
    },
  },
  {
    conceptId: 'SYMP-011',
    category: 'symptom',
    terms: {
      en: { formal: 'Diarrhea', common: ['loose stools', 'the runs', 'watery stool', 'upset stomach'] },
      es: { formal: 'Diarrea', common: ['soltura', 'churria', 'estoy suelto del estómago', 'corre que te corre'] },
      fr: { formal: 'Diarrhée', common: ['la courante', 'selles liquides', 'j\'ai la diarrhée'] },
      ar: { formal: 'إسهال', common: ['معدتي مفتوحة', 'استفراغ من تحت'] },
      zh: { formal: '腹泻', common: ['拉肚子', '拉稀', '跑肚'] },
      hi: { formal: 'दस्त', common: ['लूज़ मोशन', 'पतले दस्त', 'पेट ख़राब'] },
      tl: { formal: 'Pagtatae', common: ['nagtatae', 'LBM', 'malambot ang dumi'] },
      pt: { formal: 'Diarreia', common: ['intestino solto', 'barriga solta', 'caganeira'] },
    },
  },
  {
    conceptId: 'SYMP-012',
    category: 'symptom',
    terms: {
      en: { formal: 'Vomiting', common: ['throwing up', 'puking', 'being sick'] },
      es: { formal: 'Vómito', common: ['vomitando', 'devolviendo', 'estoy echando', 'guácala'] },
      fr: { formal: 'Vomissement', common: ['je vomis', 'j\'ai vomi', 'rendre'] },
      ar: { formal: 'قيء', common: ['استفراغ', 'ترجيع', 'بارجع'] },
      zh: { formal: '呕吐', common: ['吐了', '呕', '想吐'] },
      hi: { formal: 'उल्टी', common: ['कै', 'उल्टी हो रही है', 'वमन'] },
      tl: { formal: 'Pagsusuka', common: ['nagsusuka', 'sinusuka'] },
      pt: { formal: 'Vômito', common: ['vomitando', 'botando para fora', 'pondo para fora'] },
    },
  },
  {
    conceptId: 'SYMP-013',
    category: 'symptom',
    terms: {
      en: { formal: 'Rash', common: ['skin rash', 'red spots', 'hives', 'itchy skin'] },
      es: { formal: 'Erupción cutánea', common: ['sarpullido', 'ronchas', 'granitos', 'me salió algo en la piel'] },
      fr: { formal: 'Éruption cutanée', common: ['boutons', 'plaques rouges', 'urticaire', 'irritation'] },
      ar: { formal: 'طفح جلدي', common: ['حبوب بالجلد', 'حساسية', 'حكّة وحمرة'] },
      zh: { formal: '皮疹', common: ['起疹子', '红疹', '起红点', '皮肤过敏'] },
      hi: { formal: 'चकत्ते', common: ['दाने', 'लाल निशान', 'पित्ती', 'त्वचा पर दाने'] },
      tl: { formal: 'Pantal', common: ['may pantal', 'namumula ang balat', 'nagtatagihawat'] },
      pt: { formal: 'Erupção cutânea', common: ['manchas vermelhas', 'alergia na pele', 'urticária', 'brotoejas'] },
    },
  },
  {
    conceptId: 'SYMP-014',
    category: 'symptom',
    terms: {
      en: { formal: 'Arthralgia', common: ['joint pain', 'my joints hurt', 'stiff joints'] },
      es: { formal: 'Artralgia', common: ['dolor de articulaciones', 'me duelen las coyunturas', 'dolor de huesos'] },
      fr: { formal: 'Arthralgie', common: ['douleur articulaire', 'mal aux articulations'] },
      ar: { formal: 'ألم المفاصل', common: ['وجع مفاصل', 'مفاصلي تؤلمني', 'ركبي توجعني'] },
      zh: { formal: '关节痛', common: ['关节疼', '骨节痛', '胳膊腿疼'] },
      hi: { formal: 'जोड़ों का दर्द', common: ['जोड़ों में दर्द', 'घुटने दुख रहे हैं', 'हड्डियों में दर्द'] },
      tl: { formal: 'Pananakit ng kasukasuan', common: ['masakit ang kasukasuan', 'masakit ang buto'] },
      pt: { formal: 'Artralgia', common: ['dor nas juntas', 'dor nas articulações', 'juntas doendo'] },
    },
  },
  {
    conceptId: 'SYMP-015',
    category: 'symptom',
    terms: {
      en: { formal: 'Abdominal pain', common: ['stomach ache', 'belly pain', 'tummy hurts', 'cramps'] },
      es: { formal: 'Dolor abdominal', common: ['dolor de estómago', 'dolor de panza', 'dolor de barriga', 'retortijones'] },
      fr: { formal: 'Douleur abdominale', common: ['mal au ventre', 'mal à l\'estomac', 'crampes'] },
      ar: { formal: 'ألم بطن', common: ['وجع بطن', 'مغص', 'معدتي تؤلمني'] },
      zh: { formal: '腹痛', common: ['肚子疼', '胃疼', '肚子痛'] },
      hi: { formal: 'पेट दर्द', common: ['पेट में दर्द', 'पेट में मरोड़', 'पेट ऐंठ रहा है'] },
      tl: { formal: 'Sakit ng tiyan', common: ['masakit ang tiyan', 'kumukulo ang tiyan'] },
      pt: { formal: 'Dor abdominal', common: ['dor de barriga', 'dor no estômago', 'cólica'] },
    },
  },
  {
    conceptId: 'SYMP-016',
    category: 'symptom',
    terms: {
      en: { formal: 'Anxiety', common: ['feeling anxious', 'worried', 'nervous', 'panic'] },
      es: { formal: 'Ansiedad', common: ['angustia', 'nervios', 'estoy nervioso', 'me siento ansioso'] },
      fr: { formal: 'Anxiété', common: ['angoisse', 'je suis anxieux', 'j\'ai peur', 'crises d\'angoisse'] },
      ar: { formal: 'قلق', common: ['توتّر', 'عصبية', 'خوف', 'ضيقة نفسية'] },
      zh: { formal: '焦虑', common: ['紧张', '心慌', '担心', '心里不安'] },
      hi: { formal: 'चिंता', common: ['घबराहट', 'बेचैनी', 'दिल धड़कना', 'डर लगना'] },
      tl: { formal: 'Pagkabalisa', common: ['kinakabahan', 'nag-aalala', 'kabado'] },
      pt: { formal: 'Ansiedade', common: ['nervosismo', 'angústia', 'estou ansioso', 'inquietação'] },
    },
  },
  {
    conceptId: 'SYMP-017',
    category: 'symptom',
    terms: {
      en: { formal: 'Insomnia', common: ['can\'t sleep', 'trouble sleeping', 'waking up at night'] },
      es: { formal: 'Insomnio', common: ['no puedo dormir', 'me desvelo', 'me cuesta dormir'] },
      fr: { formal: 'Insomnie', common: ['je n\'arrive pas à dormir', 'troubles du sommeil', 'je me réveille la nuit'] },
      ar: { formal: 'أرق', common: ['ما أقدر أنام', 'سهر', 'قلة نوم'] },
      zh: { formal: '失眠', common: ['睡不着', '翻来覆去', '整夜睡不好'] },
      hi: { formal: 'अनिद्रा', common: ['नींद नहीं आती', 'रात को जागना', 'नींद की समस्या'] },
      tl: { formal: 'Hindi makatulog', common: ['hindi makatulog', 'gising buong gabi'] },
      pt: { formal: 'Insônia', common: ['não consigo dormir', 'dificuldade para dormir', 'acordo de madrugada'] },
    },
  },
  {
    conceptId: 'SYMP-018',
    category: 'symptom',
    terms: {
      en: { formal: 'Edema', common: ['swelling', 'swollen', 'puffiness', 'bloated'] },
      es: { formal: 'Edema', common: ['hinchazón', 'estoy hinchado', 'se me hinchan los pies', 'inflamado'] },
      fr: { formal: 'Œdème', common: ['gonflement', 'enflure', 'je suis gonflé', 'jambes enflées'] },
      ar: { formal: 'وذمة', common: ['تورّم', 'انتفاخ', 'رجلي منتفخة'] },
      zh: { formal: '水肿', common: ['肿了', '浮肿', '脚肿'] },
      hi: { formal: 'सूजन', common: ['सूजन आना', 'फूलना', 'पैर सूजे हुए हैं'] },
      tl: { formal: 'Pamamaga', common: ['namamaga', 'namumugto', 'lumalaki ang paa'] },
      pt: { formal: 'Edema', common: ['inchaço', 'inchado', 'pernas inchadas', 'retenção de líquido'] },
    },
  },
  {
    conceptId: 'SYMP-019',
    category: 'symptom',
    terms: {
      en: { formal: 'Paresthesia', common: ['numbness', 'tingling', 'pins and needles', 'my hand is numb'] },
      es: { formal: 'Parestesia', common: ['adormecimiento', 'hormigueo', 'se me durmió la mano', 'entumecimiento'] },
      fr: { formal: 'Paresthésie', common: ['engourdissement', 'fourmillements', 'picotements', 'ma main est engourdie'] },
      ar: { formal: 'تنميل', common: ['خدر', 'إيدي نايمة', 'تنميل بالأطراف'] },
      zh: { formal: '感觉异常', common: ['麻木', '发麻', '手脚发麻', '针刺感'] },
      hi: { formal: 'सुन्नपन', common: ['सुन्न हो गया', 'झनझनाहट', 'हाथ सो गया'] },
      tl: { formal: 'Pamamanhid', common: ['namamanhid', 'nangingilabot', 'parang tinutusok ng karayom'] },
      pt: { formal: 'Parestesia', common: ['dormência', 'formigamento', 'mão dormente', 'agulhadas'] },
    },
  },
  {
    conceptId: 'SYMP-020',
    category: 'symptom',
    terms: {
      en: { formal: 'Blurred vision', common: ['can\'t see clearly', 'fuzzy vision', 'eyes are blurry'] },
      es: { formal: 'Visión borrosa', common: ['veo borroso', 'no veo bien', 'se me nubla la vista'] },
      fr: { formal: 'Vision floue', common: ['je vois flou', 'ma vue est trouble', 'j\'ai du mal à voir'] },
      ar: { formal: 'رؤية ضبابية', common: ['نظري ضايع', 'شايف غبش', 'ما أشوف زين'] },
      zh: { formal: '视力模糊', common: ['看不清', '眼花', '眼前模糊'] },
      hi: { formal: 'धुंधला दिखना', common: ['साफ़ नहीं दिखता', 'आँखों में धुंधलापन', 'नज़र कमज़ोर'] },
      tl: { formal: 'Malabong paningin', common: ['malabo ang paningin', 'hindi malinaw ang nakikita'] },
      pt: { formal: 'Visão turva', common: ['vista embaçada', 'não enxergo direito', 'visão borrada'] },
    },
  },

  /* ──────────────────────────────────────────────────────────
     CONDITIONS (10)
     ────────────────────────────────────────────────────────── */
  {
    conceptId: 'COND-001',
    category: 'condition',
    terms: {
      en: { formal: 'Hypertension', common: ['high blood pressure', 'BP is high'] },
      es: { formal: 'Hipertensión arterial', common: ['presión alta', 'tengo la presión alta'] },
      fr: { formal: 'Hypertension artérielle', common: ['tension haute', 'haute pression'] },
      ar: { formal: 'ارتفاع ضغط الدم', common: ['ضغط عالي', 'ضغطي مرتفع'] },
      zh: { formal: '高血压', common: ['血压高', '高压'] },
      hi: { formal: 'उच्च रक्तचाप', common: ['हाई बीपी', 'ब्लड प्रेशर बढ़ा हुआ है'] },
      tl: { formal: 'Altapresyon', common: ['mataas ang presyon', 'alta presyon'] },
      pt: { formal: 'Hipertensão arterial', common: ['pressão alta', 'pressão elevada'] },
    },
  },
  {
    conceptId: 'COND-002',
    category: 'condition',
    terms: {
      en: { formal: 'Type 2 Diabetes Mellitus', common: ['type 2 diabetes', 'sugar diabetes', 'high blood sugar'] },
      es: { formal: 'Diabetes mellitus tipo 2', common: ['diabetes', 'azúcar en la sangre', 'soy diabético', 'tengo azúcar'] },
      fr: { formal: 'Diabète de type 2', common: ['diabète', 'sucre dans le sang', 'je suis diabétique'] },
      ar: { formal: 'السكري من النوع الثاني', common: ['سكري', 'مرض السكر', 'عندي سكر'] },
      zh: { formal: '2型糖尿病', common: ['糖尿病', '血糖高', '有糖尿病'] },
      hi: { formal: 'टाइप 2 मधुमेह', common: ['शुगर', 'डायबिटीज़', 'मधुमेह', 'शुगर की बीमारी'] },
      tl: { formal: 'Diyabetis tipo 2', common: ['diyabetis', 'mataas ang asukal'] },
      pt: { formal: 'Diabetes mellitus tipo 2', common: ['diabetes', 'açúcar no sangue', 'sou diabético'] },
    },
  },
  {
    conceptId: 'COND-003',
    category: 'condition',
    terms: {
      en: { formal: 'Migraine', common: ['migraine headache', 'bad headache', 'throbbing headache'] },
      es: { formal: 'Migraña', common: ['jaqueca', 'dolor de cabeza fuerte', 'migraña con aura'] },
      fr: { formal: 'Migraine', common: ['migraine', 'mal de tête intense', 'crise de migraine'] },
      ar: { formal: 'شقيقة', common: ['صداع نصفي', 'صداع شديد'] },
      zh: { formal: '偏头痛', common: ['偏头疼', '头疼得厉害', '一边头疼'] },
      hi: { formal: 'माइग्रेन', common: ['आधे सिर का दर्द', 'तेज़ सिरदर्द', 'अधकपारी'] },
      tl: { formal: 'Migraine', common: ['matinding sakit ng ulo', 'migraine'] },
      pt: { formal: 'Enxaqueca', common: ['dor de cabeça forte', 'enxaqueca com aura'] },
    },
  },
  {
    conceptId: 'COND-004',
    category: 'condition',
    terms: {
      en: { formal: 'Generalized Anxiety Disorder', common: ['anxiety disorder', 'chronic anxiety', 'GAD'] },
      es: { formal: 'Trastorno de ansiedad generalizada', common: ['ansiedad', 'nervios crónicos', 'angustia constante'] },
      fr: { formal: 'Trouble anxieux généralisé', common: ['anxiété généralisée', 'trouble anxieux', 'angoisse chronique'] },
      ar: { formal: 'اضطراب القلق العام', common: ['قلق مزمن', 'توتّر دائم', 'اضطراب نفسي'] },
      zh: { formal: '广泛性焦虑障碍', common: ['焦虑症', '总是担心', '心里不踏实'] },
      hi: { formal: 'सामान्यीकृत चिंता विकार', common: ['एंग्ज़ायटी', 'हमेशा चिंता', 'घबराहट की बीमारी'] },
      tl: { formal: 'Pangkalahatang anxiety disorder', common: ['anxiety', 'laging kinakabahan', 'sobrang pag-aalala'] },
      pt: { formal: 'Transtorno de ansiedade generalizada', common: ['ansiedade crônica', 'TAG', 'vive preocupado'] },
    },
  },
  {
    conceptId: 'COND-005',
    category: 'condition',
    terms: {
      en: { formal: 'Urinary Tract Infection', common: ['UTI', 'bladder infection', 'burning when I pee'] },
      es: { formal: 'Infección de vías urinarias', common: ['infección urinaria', 'infección de orina', 'me arde al orinar', 'cistitis'] },
      fr: { formal: 'Infection urinaire', common: ['infection urinaire', 'cystite', 'ça brûle quand j\'urine'] },
      ar: { formal: 'التهاب المسالك البولية', common: ['التهاب بول', 'حرقان بول', 'يحرقني لما أتبوّل'] },
      zh: { formal: '尿路感染', common: ['尿道炎', '尿痛', '小便疼'] },
      hi: { formal: 'मूत्र मार्ग संक्रमण', common: ['यूटीआई', 'पेशाब में जलन', 'यूरिन इन्फ़ेक्शन'] },
      tl: { formal: 'Impeksyon sa ihi', common: ['UTI', 'masakit umihi', 'makirot ang ihi'] },
      pt: { formal: 'Infecção do trato urinário', common: ['infecção urinária', 'cistite', 'ardência ao urinar'] },
    },
  },
  {
    conceptId: 'COND-006',
    category: 'condition',
    terms: {
      en: { formal: 'Asthma', common: ['asthma', 'breathing problems', 'wheezing'] },
      es: { formal: 'Asma', common: ['asma', 'me silba el pecho', 'fatiga', 'no puedo respirar'] },
      fr: { formal: 'Asthme', common: ['asthme', 'crise d\'asthme', 'je siffle en respirant'] },
      ar: { formal: 'ربو', common: ['ربو', 'حساسية صدر', 'أزمة تنفّسية'] },
      zh: { formal: '哮喘', common: ['哮喘', '气喘', '喘不过气'] },
      hi: { formal: 'दमा', common: ['अस्थमा', 'दमा', 'साँस की बीमारी', 'साँस में सीटी'] },
      tl: { formal: 'Hika', common: ['hika', 'hirap huminga', 'may huni sa dibdib'] },
      pt: { formal: 'Asma', common: ['asma', 'chiado no peito', 'bronquite asmática'] },
    },
  },
  {
    conceptId: 'COND-007',
    category: 'condition',
    terms: {
      en: { formal: 'Gastroesophageal Reflux Disease', common: ['GERD', 'acid reflux', 'heartburn'] },
      es: { formal: 'Enfermedad por reflujo gastroesofágico', common: ['reflujo', 'agruras', 'acidez', 'me quema el pecho'] },
      fr: { formal: 'Reflux gastro-œsophagien', common: ['reflux', 'brûlures d\'estomac', 'remontées acides'] },
      ar: { formal: 'الارتجاع المعدي المريئي', common: ['حموضة', 'حرقة المعدة', 'ارتجاع'] },
      zh: { formal: '胃食管反流病', common: ['反酸', '烧心', '胃酸倒流'] },
      hi: { formal: 'गैस्ट्रोइसोफ़ेजियल रिफ़्लक्स', common: ['एसिडिटी', 'सीने में जलन', 'खट्टी डकार'] },
      tl: { formal: 'GERD', common: ['acid reflux', 'masakit ang sikmura', 'umaahon ang asido'] },
      pt: { formal: 'Doença do refluxo gastroesofágico', common: ['refluxo', 'azia', 'queimação'] },
    },
  },
  {
    conceptId: 'COND-008',
    category: 'condition',
    terms: {
      en: { formal: 'Major Depressive Disorder', common: ['depression', 'feeling depressed', 'feeling down'] },
      es: { formal: 'Trastorno depresivo mayor', common: ['depresión', 'me siento triste', 'estoy deprimido', 'no tengo ganas de nada'] },
      fr: { formal: 'Trouble dépressif majeur', common: ['dépression', 'je suis déprimé', 'je broie du noir'] },
      ar: { formal: 'اضطراب اكتئابي', common: ['اكتئاب', 'حزن شديد', 'ما عندي رغبة بشيء'] },
      zh: { formal: '重性抑郁障碍', common: ['抑郁症', '心情低落', '不想动'] },
      hi: { formal: 'अवसाद', common: ['डिप्रेशन', 'मन उदास', 'कुछ अच्छा नहीं लगता'] },
      tl: { formal: 'Depresyon', common: ['malungkot', 'walang gana', 'depresyon'] },
      pt: { formal: 'Transtorno depressivo maior', common: ['depressão', 'tristeza profunda', 'sem vontade de nada'] },
    },
  },
  {
    conceptId: 'COND-009',
    category: 'condition',
    terms: {
      en: { formal: 'Anemia', common: ['low iron', 'low blood count', 'anemic'] },
      es: { formal: 'Anemia', common: ['anemia', 'falta de hierro', 'sangre débil', 'estoy anémica'] },
      fr: { formal: 'Anémie', common: ['anémie', 'manque de fer', 'je suis anémié'] },
      ar: { formal: 'فقر الدم', common: ['أنيميا', 'نقص حديد', 'دمي ضعيف'] },
      zh: { formal: '贫血', common: ['贫血', '缺铁', '血不够'] },
      hi: { formal: 'एनीमिया', common: ['ख़ून की कमी', 'आयरन की कमी', 'कमज़ोर ख़ून'] },
      tl: { formal: 'Anemia', common: ['kulang sa dugo', 'anemia', 'maputla'] },
      pt: { formal: 'Anemia', common: ['anemia', 'falta de ferro', 'sangue fraco'] },
    },
  },
  {
    conceptId: 'COND-010',
    category: 'condition',
    terms: {
      en: { formal: 'Bronchitis', common: ['chest cold', 'bronchitis', 'deep cough'] },
      es: { formal: 'Bronquitis', common: ['bronquitis', 'pecho cargado', 'tos de pecho'] },
      fr: { formal: 'Bronchite', common: ['bronchite', 'toux grasse', 'infection des bronches'] },
      ar: { formal: 'التهاب الشعب الهوائية', common: ['التهاب قصبات', 'كحّة صدر', 'صدري محمّل'] },
      zh: { formal: '支气管炎', common: ['气管炎', '支气管发炎', '咳嗽不停'] },
      hi: { formal: 'ब्रोंकाइटिस', common: ['ब्रोंकाइटिस', 'छाती में बलगम', 'सीने की खांसी'] },
      tl: { formal: 'Brongkitis', common: ['brongkitis', 'malalim na ubo', 'may plema sa dibdib'] },
      pt: { formal: 'Bronquite', common: ['bronquite', 'catarro no peito', 'tosse de peito'] },
    },
  },

  /* ──────────────────────────────────────────────────────────
     PROCEDURES (5)
     ────────────────────────────────────────────────────────── */
  {
    conceptId: 'PROC-001',
    category: 'procedure',
    terms: {
      en: { formal: 'Cesarean Section', common: ['C-section', 'cesarean delivery'] },
      es: { formal: 'Cesárea', common: ['cesárea', 'me van a hacer cesárea', 'operación para el parto'] },
      fr: { formal: 'Césarienne', common: ['césarienne', 'accouchement par césarienne'] },
      ar: { formal: 'عملية قيصرية', common: ['قيصرية', 'ولادة قيصرية'] },
      zh: { formal: '剖宫产', common: ['剖腹产', '刨妇产'] },
      hi: { formal: 'सीज़ेरियन सेक्शन', common: ['सिज़ेरियन', 'ऑपरेशन से डिलीवरी'] },
      tl: { formal: 'Cesarean Section', common: ['CS', 'opera', 'cesarean'] },
      pt: { formal: 'Cesárea', common: ['cesárea', 'cesariana', 'parto cirúrgico'] },
    },
  },
  {
    conceptId: 'PROC-002',
    category: 'procedure',
    terms: {
      en: { formal: 'Appendectomy', common: ['appendix removal', 'appendix surgery'] },
      es: { formal: 'Apendicectomía', common: ['operación del apéndice', 'me sacaron el apéndice'] },
      fr: { formal: 'Appendicectomie', common: ['opération de l\'appendicite', 'ablation de l\'appendice'] },
      ar: { formal: 'استئصال الزائدة الدودية', common: ['عملية الزايدة', 'شلت الزايدة'] },
      zh: { formal: '阑尾切除术', common: ['切阑尾', '割盲肠'] },
      hi: { formal: 'अपेंडेक्टमी', common: ['अपेंडिक्स का ऑपरेशन', 'अपेंडिक्स निकालना'] },
      tl: { formal: 'Appendectomy', common: ['opera sa apendiks', 'tinanggal ang apendiks'] },
      pt: { formal: 'Apendicectomia', common: ['cirurgia do apêndice', 'tirar o apêndice'] },
    },
  },
  {
    conceptId: 'PROC-003',
    category: 'procedure',
    terms: {
      en: { formal: 'Blood Test', common: ['blood work', 'lab test', 'blood draw'] },
      es: { formal: 'Análisis de sangre', common: ['examen de sangre', 'me sacaron sangre', 'laboratorio'] },
      fr: { formal: 'Prise de sang', common: ['analyse de sang', 'bilan sanguin', 'on m\'a pris du sang'] },
      ar: { formal: 'تحليل دم', common: ['فحص دم', 'سحبوا دم', 'تحاليل'] },
      zh: { formal: '验血', common: ['抽血', '血液检查', '化验'] },
      hi: { formal: 'रक्त परीक्षण', common: ['ख़ून की जांच', 'ब्लड टेस्ट', 'लैब टेस्ट'] },
      tl: { formal: 'Blood test', common: ['pagkuha ng dugo', 'blood test', 'lab test'] },
      pt: { formal: 'Exame de sangue', common: ['hemograma', 'tiraram sangue', 'exame laboratorial'] },
    },
  },
  {
    conceptId: 'PROC-004',
    category: 'procedure',
    terms: {
      en: { formal: 'Radiography', common: ['X-ray', 'getting an X-ray'] },
      es: { formal: 'Radiografía', common: ['rayos X', 'me sacaron una placa', 'radiografía'] },
      fr: { formal: 'Radiographie', common: ['radio', 'rayons X', 'on m\'a fait une radio'] },
      ar: { formal: 'تصوير بالأشعة السينية', common: ['أشعة', 'صورة أشعة', 'إكس راي'] },
      zh: { formal: 'X射线检查', common: ['拍X光', '拍片子', '照片子'] },
      hi: { formal: 'एक्स-रे', common: ['एक्स-रे', 'एक्सरे कराना'] },
      tl: { formal: 'X-ray', common: ['X-ray', 'nagpa-X-ray'] },
      pt: { formal: 'Radiografia', common: ['raio-X', 'tirar chapa', 'radiografia'] },
    },
  },
  {
    conceptId: 'PROC-005',
    category: 'procedure',
    terms: {
      en: { formal: 'Endoscopy', common: ['scope', 'camera down the throat', 'upper GI scope'] },
      es: { formal: 'Endoscopia', common: ['endoscopia', 'la cámara del estómago', 'me metieron una cámara'] },
      fr: { formal: 'Endoscopie', common: ['endoscopie', 'fibroscopie', 'on m\'a passé une caméra'] },
      ar: { formal: 'تنظير', common: ['منظار', 'منظار معدة', 'كاميرا المعدة'] },
      zh: { formal: '内窥镜检查', common: ['胃镜', '做胃镜', '照胃镜'] },
      hi: { formal: 'एंडोस्कोपी', common: ['दूरबीन से जांच', 'पेट की दूरबीन', 'एंडोस्कोपी'] },
      tl: { formal: 'Endoscopy', common: ['endoscopy', 'camera sa tiyan'] },
      pt: { formal: 'Endoscopia', common: ['endoscopia', 'exame do estômago', 'câmera no estômago'] },
    },
  },
]
